### ISSUE TITLE
Language/syntax highlighting on restart

### ISSUE THREAD

**Issue by AM-ops** [rudolphventer/GreenTea#3]
When GreenTea is run the most recent document is opened but language/syntax highlighting not saved. However in previous session a language was chosen and was wondering if that info is saved. Or at least in current version.

**Comment by rudolphventer** [comment]
What OS are you using?
Could you check if saving your selected theme works too?
If not it could be an issue with how localstorage is used on your platform

**Comment by AM-ops** [comment]
Windows 7 (Haven't tried on 10 yet)
Theme works perfectly. Whichever theme was chosen it stays the same.
It's just the language/syntax highlighting

**Comment by rudolphventer** [comment]
Wait, are you picking a custom syntax highlighting mode (that is not autodetected) and then restarting the program? 

If that is the case then it is working as intended, you would not want to be working on a text document  and then having no syntax highlighting on the Python document you open next because it is still using the last syntax mode.

**Comment by AM-ops** [comment]
yep autodetect did not work on a LaTeX file I tested. When I restarted the program (after language was chosen in previous session) it opened the LaTeX file but no syntax highlighting was done.
